# Generated by Django 4.1.5 on 2023-01-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='blog',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
