# Generated by Django 4.1.5 on 2023-02-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='und_score_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='und_score_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='und_score_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='und_score_up',
            field=models.IntegerField(default=0),
        ),
    ]
